name: fingerprint
description: A package for creating fingerprints of any environment.
version: 0.1.0
repository: https://github.com/cardinal-run/fingerprint
issue_tracker: https://github.com/cardinal-run/fingerprint/issues
topics: [fingerprint, detection, identification, fingerprinting]

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  crypto: ^3.0.5
  device_info_plus: ^11.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  coverage: ^1.10.0
  device_info_plus_platform_interface: ^7.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.25.7
  very_good_analysis: ^6.0.0
